### ISSUE TITLE
This error originated either by throwing inside of an async function without a catch block

### ISSUE THREAD

**Issue by quangArchiviet** [Brakebein/node-three-gltf#4]
```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

An error occurs when trying to load [this model](https://archisketch-resources.s3.ap-northeast-2.amazonaws.com/vrstyler/1664764805879_427285/LittlestTokyo.glb).

The model shows normally when using GLTFLoader and useGLTF on the Frontend.

**Comment by quangArchiviet** [comment]
<img width="783" alt="Screen Shot 2022-10-04 at 09 17 38" src="https://user-images.githubusercontent.com/68496597/193720331-691d6c2d-10d7-4f07-9947-14205b7a45da.png">

**Comment by Brakebein** [comment]
I just released version 1.3.0. I found the bug within GLTFLoader not passing the attribute types (specific to animations) to DRACOLoader. It should work now.

**Comment by quangArchiviet** [comment]
<img width="871" alt="Screen Shot 2022-10-04 at 21 22 30" src="https://user-images.githubusercontent.com/68496597/193844879-90e036ac-fe76-4157-9cb2-f70be6bbdfe2.png">

Problem solved. But don't know why the model reversed. 😅

**Comment by Brakebein** [comment]
In my test render environment, the model looks fine and the orientation is correct. However, I don't apply any animations. Maybe, it has to do something with the animations wrongly applied?

**Comment by quangArchiviet** [comment]
Look like `toJSON()` didn't copy `quaternion` and `rotation` of the model objects. 

```
Quaternion {
  isQuaternion: true,
  _x: -0.7071067811865475,
  _y: 0,
  _z: 0,
  _w: 0.7071067811865476,
  _onChangeCallback: [Function: onQuaternionChange]
}
```

**Comment by quangArchiviet** [comment]
Ahhhhhh ... even i push quaternion and rotation after convert the Scene to JSON format ... ObjectLoad parse still didn't use it ...

**Comment by Brakebein** [comment]
Have a look into the code: `.toJSON()` only takes the matrix ([Object3D.js#L693](https://github.com/mrdoob/three.js/blob/master/src/core/Object3D.js#L693)). And if a matrix is defined, it won't consider any quaternion or rotation while parsing ([ObjectLoader.js#L943-L957](https://github.com/mrdoob/three.js/blob/master/src/loaders/ObjectLoader.js#L943-L957)).
`matrixAutoUpdate` is either `false` or `undefined`, so in ObjectLoader the matrix won't get overridden by `matrix.decompose()` (on L948).

So, pushing quaternion and rotation won't do anything.

But it can be that the matrix is not set yet when converting to json. This is usually done automatically when you call `renderer.render()`. Because you won't call `render()` at the backend, you have to trigger this manually. So, before converting to json, try to update the matrices:

```js
loader.load(file, (gltf) => {
  gltf.scene.updateMatrixWorld(true);
  // ...
});
```

**Comment by quangArchiviet** [comment]
Problem solved. I tried to update Matrix World at the frontend ... after converting to JSON ... That's why nothing changes... haha
