### ISSUE TITLE
Buffer.buffer contains incorrect data

### ISSUE THREAD

**Issue by misty000** [Brakebein/node-three-gltf#6]
I found geometry.attributes data is wrong.
The reason is Buffer.buffer 's data is ArrayBuffer(8192).

![f1fdab6ae68dd35f24cc4f5c67f79e5](https://user-images.githubusercontent.com/3632834/205078404-19b5a14e-3e3f-4bba-b276-49b1a5c98a58.png)

node version: 16
"dependencies": {
    "base64-js": "1.5.1",
    "node-three-gltf": "1.3.0",
    "three": "0.147.0"
  }

**Comment by misty000** [comment]
no matter what the base64 string is, Buffer.buffer is always the same

**Comment by Brakebein** [comment]
First, I wasn't sure about what the issue is, since `Buffer.buffer` is of course an instance of `ArrayBuffer`. But I actually have one test file which failed to load and I couldn't find the reason why, even though other files from the same converter output didn't cause any issues. So, node.js `Buffer.from(string[, encoding])` obviously has some problems with binary data. The `base64-js` package did the trick and my problematic gltf file finally loaded. So, thanks for pointing out.
